-- CREATE TABLE: meter_accounts
-- Description: Tracks individual customer accounts linked to physical water meters.
-- All data populated into this schema is 100% synthetic for testing purposes.

CREATE TABLE meter_accounts (
    account_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name     VARCHAR2(100) NOT NULL,
    service_address   VARCHAR2(255) NOT NULL,
    phone_number      VARCHAR2(15),
    account_status    VARCHAR2(10) DEFAULT 'ACTIVE',
    connection_date   DATE DEFAULT SYSDATE,
    
    -- Constraint to ensure data integrity for account status
    CONSTRAINT chk_account_status CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
);
